filter {
  grok {
    match => {
      "message" => "%{NUMBER:[squid][timestamp]}\s+%{NUMBER:[squid][elapsed_ms]:int}\s+%{IP:[source][ip]}\s+%{WORD:[squid][action]}/%{NUMBER:[http][response][status_code]:int}\s+%{NUMBER:[http][response][bytes]:int}\s+%{WORD:[http][request][method]}\s+%{NOTSPACE:[url][original]}\s+%{NOTSPACE:[user][name]}\s+%{NOTSPACE:[squid][peer_action]}/%{NOTSPACE:[destination][ip]}\s+%{NOTSPACE:[http][response][mime_type]}"
    }
    add_tag => ["squid"]
    tag_on_failure => ["_grokparsefailure", "squid_failed"]
    id => "squid"
  }

  date {
    match  => ["[squid][timestamp]", "UNIX"]
    target => "@timestamp"
  }

  mutate {
    remove_field => ["[squid][timestamp]"]
  }
}
